### ISSUE TITLE
End tangents

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [thibauts/b-spline#4]
I've just found your code and think that it is really good. Currently I'm trying to interpolate Autodesk's dxf file splines and your code comes really close except that Autodesk defines the end tangents of their splines and the length of their knot value fails your test on line 26.

I've been trying to figure out how to implement having the end tangent defined. Is there a way to add extra control points to have this work out correctly or should it be done in a different way?

I've been working on this for a while and still have not been able to figure it out. Please let me know if you know any way to interpolate this kind of spline.
Thank you

Here is an example of an Autodesk b-spline:

Autodesk spline cad drawing
![spline](https://cloud.githubusercontent.com/assets/10747532/15441580/b568af82-1ea9-11e6-8b8d-4308c7e8ef8e.jpg)

Interpolation using your b-spline library
![spline_interpolation](https://cloud.githubusercontent.com/assets/10747532/15441581/b56a3dac-1ea9-11e6-906f-c33450d62c76.png)

**Spline Properties**
degree
3

starttangent
[-0.4138029443011841, 0.9103664774626047]
angle 1.9974238199217729 rad

endtangent
[0.8422714006615115, 0.539053696423367]
angle 0.5693131911006616 rad

controlpoints
[[2.399185827365247, 3.556238220882021], [1.79819140306395, 4.878425954344872], [3.793761079285986, 10.00772218210104], [9.597527631961984, 2.634051205137613], [-1.014386849068146, -0.7575600644211504], [-0.0580977089595729, 7.39060578138084], [1.891006407840181, 8.638032416132681]]
number of controlpoints 7

fitpoints
[[2.399185827365247, 3.556238220882021], [4.039879381831888, 7.592634753109687], [7.045397663022992, 3.861145872597061], [1.411865812287976, 1.712272898605353], [1.891006407840181, 8.638032416132681]]
number of fitpoints 5

knots
[0.0, 0.0, 0.0, 0.0, 4.357105955223939, 9.148467912325835, 15.17792362338283, 22.1202374022988, 22.1202374022988, 22.1202374022988, 22.1202374022988]
number of knots 11

weights
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
number of weights 7

normalvector
(0.0, 0.0, 1.0)

is_closed
False

is_periodic
False

is_rational
False

is_planar
True

is_linear
False

**Comment by thibauts** [comment]
Hi ! Looking up the DXF specs, it looks like the end tangents can be omitted in the file, so maybe they aren't used in the spline computation. Then, degree 3 equates to order 4, are you using the right number here ? This may explain why you get the line 26 error.

I was worried by the fit points, but it looks like they are only a tool for users to define a spline without defining the control frame. So the control frame would be computed from them by the CAD software, and both stored in the DXF file so the software doesn't "forget" the original user input. In other words, they most probably aren't used in the computation. But you probably already know this.

Let me know how this goes !

**Comment by BebeSparkelSparkel** [comment]
Thanks so much! Put so much time in trying to figure this out.
What did you originally write this for?

**Comment by thibauts** [comment]
Glad I could help you ! Do you get the correct curve now ?

I wrote this module in part because I wanted to crack how B-splines worked, and in part because we needed them at my previous employer. I don't have an extensive background in mathematics so this was a great (and quite tough) challenge ! The algorithm is hard to get right and there's not one place where you can get complete information about how it works, or sample code, even in another language.

**Comment by BebeSparkelSparkel** [comment]
The curve is perfect now! Now I'm just getting it working in my python code (yeah js in py). Once I get the wrapper I'll send it to you.

The search was hard for this. I got a large part of a spline interpolator written in python but the last 5% made me give up; I bet having the wrong order didn't help either.

Thanks again for the help

**Comment by thibauts** [comment]
Are you sure there is no way to constain the end tangents in autocad ? Reading a bit more in autodesk docs I came to be in doubt.

Are you calling JS code from python ? You could probably translate the code without too much pain if you wish so

**Comment by BebeSparkelSparkel** [comment]
Not sure about constaining the end tangents, I'll be running more test to make sure that the autodesk and interpolated splines match.

I've transposed the code and am currently running a test to compare the results and am getting results that have too much error in them, so still testing to get conformity.
https://github.com/BebeSparkelSparkel/b-spline
