### ISSUE TITLE
add some simple testing to make sure changes to the library don't break intended behaviour

### ISSUE THREAD

**Issue by Pomax** [thibauts/b-spline#9]
subject says it all really.

@thibauts nothing super creative here, just figured it'd be worth commiting before I ever so slightly simplify index.js by removing the rebinding on `weights[i]` to `v[i][d]`, since we never discard `weights[i]` and only call `v[s][d]` all the way at the end, where `weights[s]` does the exact same thing.

**Comment by thibauts** [comment]
I'm really busy currently, don't hesitate to merge and publish..

**Comment by Pomax** [comment]
done and done. The tests already invalidated the other PR I filed because I missed a crucial bit of how the De Boor pyramid got constructed =)
